<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/
	'App/Models/BaseModel.php',
	'App/Models/Feedlist.php',
	'App/Models/Pin.php',
	'App/Models/User.php',
	'App/Providers/GuestServiceProvider.php',
	'App/Controllers/BaseController.php'

);