<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/
	'app/models/BaseModel.php',
	'app/models/Feedlist.php',
	'app/models/Pin.php',
	'app/models/User.php',
	'app/providers/GuestServiceProvider.php',
	'app/controllers/BaseController.php'

);